### ISSUE TITLE
"The Lesser Faydark" invalid zone?

### ISSUE THREAD

**Issue by Sicprofundus** [brainiac/MQ2EasyFind#13]
![image](https://user-images.githubusercontent.com/48923666/134488813-e022ac41-76be-4f48-a198-d4995ef210d2.png)

/travelto "Lesser Faydark" fails (it should)
/travelto "The Lesser Faydark fails (it shouldn't)
/travelto lfaydark works (it should)

lfaydark

in The Lesser Faydark if i do th following:
(only showing this to demonstrate the two "The Lesser Faydark" reporting two different things)
/travelto lfaydark it says "You are already in The Lesser Faydark (correct)
/travelto "The Lesser Faydark" results in Invalid Zone
![image](https://user-images.githubusercontent.com/48923666/134489053-d19025e7-8a4f-41b7-99dc-3127ecdbe101.png)

**Comment by brainiac** [comment]
duplicate issue (#24)
