### ISSUE TITLE
Group travel sometimes fails to find the zone you select

### ISSUE THREAD

**Issue by Sicprofundus** [brainiac/MQ2EasyFind#3]
Doing the group travel "control+shift+click" to make the group run, it can't find the zone
Doing the solo travel "control+click" to make just myself run, it can find the zones and runs to it
![image](https://user-images.githubusercontent.com/48923666/132536397-35ff216e-2827-4d15-972f-bca9bb4b4372.png)

```
Per convo with brain it appears it is searching for the zone by zone name, and not the label - and the label itself is a stopgap anyhow
```

Per Hytiek this issue also occurs trying to go to feerott the dream
```
trying to get my crew to the Dream / Feerrott - using ctrl+shift+left click; but toons go to normal zone; not the dream - wondered if it should work or still to be enabled?
```

**Comment by brainiac** [comment]
how guild halls works in easyfind will be replaced soon, once I finish fleshing out the real estate api

**Comment by hytiek** [comment]
just to add Feerrott and The Dream version of it

**Comment by brainiac** [comment]
issue occurs when name of label doesn't match the name of the zone.
