### ISSUE TITLE
Connection missing: (ToV) Eastern Wastes -> (ToV) Sleeper's Tomb

### ISSUE THREAD

**Issue by cvanwie** [brainiac/MQ2EasyFind#35]
Currently there's no connection available.

Sleeper's tomb is accessed via:

![image](https://user-images.githubusercontent.com/10496663/141176201-3db74a39-5e20-40fb-ad24-741d2c0f89ae.png)

**Comment by brainiac** [comment]
I added the connection but let me know if it doesn't work right, i wasn't able to test it.
