### ISSUE TITLE
Erudin to Erud's crossing 

### ISSUE THREAD

**Issue by jessebevil** [brainiac/MQ2EasyFind#46]
Issue traveling to Erud's Crossing. My basic assumption is because of teleporting pads in Erudin causing a disconnect from zoning coming from Tox to the other end of the zone. The path requires 2 teleporters and a translocator (Translocator Eniela). The only option the translocator offers is [Erud's Crossing]

**Comment by brainiac** [comment]
The teleport pads are more of a nav/mesh issue. The connection to erud's crossing should already be there.
