### ISSUE TITLE
Stone hive to blightfire moors

### ISSUE THREAD

**Issue by jessebevil** [brainiac/MQ2EasyFind#47]
Traveled to Stone Hive from Blightfire Moors just fine, but didn't want to travel back. I loaded the mesh and confirmed connection with mesh along the route back from middle of the zone, so didn't appear to be mesh related.

**Comment by jessebevil** [comment]
Update on this. Appears the default location puts you to the right (when facing out) of the walkable area. 
I manually used `-1754 -886 38`
and was able to zone successfully. Obtained location by clicking the spot in MeshGen

**Comment by brainiac** [comment]
can you format that as something i can add to the yaml file?

**Comment by jessebevil** [comment]
moors:
        -   type: ZoneConnection
            location: [-1754, -886, 38]
            targetZone: stonehive
