### ISSUE TITLE
Emu - Random EQ Client Crashing with MQ2EasyFind enabled

### ISSUE THREAD

**Issue by andrew2241** [brainiac/MQ2EasyFind#52]
This is for the EMU Client and MQNext build
I am experiencing random client crashing when MQ2EasyFind is enabled. The following is what happens:

Login using MQ2AutoLogin and Innerspace/ISBoxer profiles -> character reaches Character Select -> Loading splash screen -> as soon as the world is about the load is when the crash occurs. 

It doesn't happen for every character and it doesn't happen to the same characters every time. I then try to use the auto login again and sometimes the character successfully loads and sometimes it doesn't.  I am testing this loading 36 characters.

My troubleshooting steps include:

Reverting my Macroquest.ini file back to default. I loaded all 36 characters without a crash.
Adding in the plugins 1 by 1 and then attempting to load characters until I receive a crash.
The crashes started happening again once I enabled MQ2EasyFind and disappeared when I disabled it.

**Comment by brainiac** [comment]
moved here https://github.com/macroquest/macroquest/issues/609
